@startuml
'https://plantuml.com/class-diagram



 Main43 <|-- BuildWebsite

 Main43 : main()
 BuildWebsite : BuildWebsite((String site, String author, char js, char css)
 BuildWebsite : createFolder(String path, char js, char css)


@enduml